/// Flutter icons VetIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VetIcons
///      fonts:
///       - asset: fonts/VetIcons.ttf
///
/// 
///+++++++++++++++++++++++++/////
///
/// Custom Icons From Figma /////
import 'package:flutter/widgets.dart';

class VetIcons {
  VetIcons._();

  static const _kFontFam = 'VetIcons';
  static const String? _kFontPkg = null;

/// иконка для Регистрации животный
  static const IconData vet_animal_registration = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
/// иконка для Миграций(пока не работает)
  static const IconData vet_reference = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
